import Image from "next/image";
import Link from "next/link";

export const metadata = { title: "AI SDLC Governance Case Study | Utham Kumar" };

export default function AiSdlcGovernanceCaseStudy() {
  return <main className="case-page">
    <header className="case-nav"><Link href="/">← Utham Kumar</Link><span>Engineering Intelligence Lab / AIG-004</span></header>
    <section className="case-hero"><span className="kicker">Enterprise reference implementation</span><h1>AI SDLC Governance</h1><p>Move AI from experimentation to accountable production.</p><div><span><small>Role demonstrated</small><b>AI governance operating-system architect</b></span><span><small>Release</small><b>v0.1.0</b></span><span><small>Data policy</small><b>100% synthetic</b></span></div></section>
    <section className="case-image"><Image src="/ai-sdlc-governance.png" alt="AI SDLC Governance executive governance posture view" width={1536} height={1024} priority /></section>
    <section className="case-content"><aside><span className="section-number">THE CHALLENGE</span></aside><div><h2>AI adoption scales faster than governance evidence.</h2><p>Leaders can have dozens of AI experiments moving through discovery, development, evaluation, and production without a shared view of ownership, risk tier, control evidence, exceptions, or readiness. The challenge is not adding another approval board. It is building governance into the delivery system so teams can move quickly while leaders retain accountable control.</p></div></section>
    <section className="case-system"><span className="section-number">THE OPERATING SYSTEM</span><div className="case-grid"><article><b>01</b><h3>Register and risk-tier use cases</h3><p>Every AI use case has an accountable owner, business purpose, data classification, criticality, model approach, and lifecycle stage.</p></article><article><b>02</b><h3>Make lifecycle controls explicit</h3><p>Required evidence is visible from intake through production across privacy, safety, security, SDLC controls, and operations.</p></article><article><b>03</b><h3>Explain readiness and hard rules</h3><p>Six weighted dimensions, status thresholds, and non-negotiable caps show exactly why a use case is ready, conditional, under review, or stopped.</p></article><article><b>04</b><h3>End governance in decisions</h3><p>Exceptions, blockers, top drivers, recommended actions, and a no-key executive brief turn governance evidence into accountable action.</p></article></div><p className="case-ecosystem"><b>Illustrative enterprise evidence model:</b> Jira and Confluence · CI/CD pipelines · model evaluation and red-team evidence · security and privacy reviews · observability and incident controls · executive decision records. The public demo uses synthetic data, no API keys, and no employer connections.</p></section>
    <section className="case-content"><aside><span className="section-number">LEADERSHIP SIGNAL</span></aside><div><h2>This is AI governance designed as an operating system—not a policy document.</h2><p>The application demonstrates how a senior or principal TPM can scale responsible AI adoption across product, engineering, risk, security, privacy, and operations: establish a common control model, preserve speed through explainability, surface exceptions early, and make production decisions defensible.</p><div className="case-actions"><a href="https://ai-sdlc-governance.uthamkumar.info" target="_blank" rel="noreferrer">Open application when published ↗</a><Link href="/#work">Return to selected work</Link></div></div></section>
    <footer className="case-footer"><span>AI SDLC Governance · Engineering Intelligence Lab</span><Link href="/">uthamkumar.info →</Link></footer>
  </main>;
}
