import Link from "next/link";
import Image from "next/image";

export const metadata = { title: "Engineering Control Tower Case Study | Utham Kumar" };

export default function EngineeringControlTowerCaseStudy() {
  return <main className="case-page">
    <header className="case-nav"><Link href="/">← Utham Kumar</Link><span>Engineering Intelligence Lab / ECT-003</span></header>
    <section className="case-hero"><span className="kicker">Enterprise reference implementation</span><h1>Engineering Control Tower</h1><p>Seeing portfolio health—and making the move.</p><div><span><small>Role demonstrated</small><b>Portfolio operating-system architect</b></span><span><small>Release</small><b>v0.1.0</b></span><span><small>Data policy</small><b>100% synthetic</b></span></div></section>
    <section className="case-image"><Image src="/engineering-control-tower.png" alt="Engineering Control Tower executive portfolio intelligence view" width={1536} height={1024} priority /></section>
    <section className="case-content"><aside><span className="section-number">THE CHALLENGE</span></aside><div><h2>Portfolio status is abundant. Intervention intelligence is scarce.</h2><p>Engineering leaders receive delivery, quality, reliability, security, and capacity signals from many systems. The challenge is not collecting more status. It is explaining which outcomes are exposed, what shared constraint is limiting performance, and which leadership move will change the signal.</p></div></section>
    <section className="case-system"><span className="section-number">THE OPERATING SYSTEM</span><div className="case-grid"><article><b>01</b><h3>Anchor on outcomes</h3><p>Program health begins with outcome confidence, target evidence, investment context, and accountable teams.</p></article><article><b>02</b><h3>Explain health</h3><p>Six visible dimensions and four hard governance rules make scoring reproducible without replacing leadership judgment.</p></article><article><b>03</b><h3>Find the constraint</h3><p>Demand, capacity, and downstream exposure reveal shared bottlenecks before they appear as isolated team misses.</p></article><article><b>04</b><h3>Make the move</h3><p>Every intervention has a decision, owner, expected impact, and verification window so governance ends in action.</p></article></div><p className="case-ecosystem"><b>Illustrative enterprise evidence model:</b> Jira and portfolio planning · CI/CD and DevSecOps signals · service catalogs · incident and reliability evidence · cloud and observability platforms · executive decision records. The public demo uses synthetic data and no employer connections.</p></section>
    <section className="case-content"><aside><span className="section-number">LEADERSHIP SIGNAL</span></aside><div><h2>This is engineering governance designed as a decision product.</h2><p>The application demonstrates how a senior or principal TPM can create a shared executive view across multiple programs and teams: make outcomes legible, expose system constraints, intervene where leverage is highest, and verify that the decision improved engineering performance.</p><div className="case-actions"><a href="https://engineering-control-tower.vercel.app" target="_blank" rel="noreferrer">Open live reference implementation ↗</a><Link href="/#work">Return to selected work</Link></div></div></section>
    <footer className="case-footer"><span>Engineering Control Tower · Engineering Intelligence Lab</span><Link href="/">uthamkumar.info →</Link></footer>
  </main>;
}
