import Image from "next/image";
import Link from "next/link";

export const metadata = { title: "Engineering Experience Index Case Study | Utham Kumar" };

export default function EngineeringExperienceIndexCaseStudy() {
  return <main className="case-page">
    <header className="case-nav"><Link href="/">← Utham Kumar</Link><span>Engineering Intelligence Lab / EE-006</span></header>
    <section className="case-hero"><span className="kicker">Enterprise reference implementation</span><h1>Engineering Experience Index</h1><p>Turn engineering friction into visible leadership decisions.</p><div><span><small>Role demonstrated</small><b>Developer-experience operating-model architect</b></span><span><small>Release</small><b>v0.1.0</b></span><span><small>Data policy</small><b>100% synthetic</b></span></div></section>
    <section className="case-image"><Image src="/engineering-experience-index.png" alt="Engineering Experience Index developer effectiveness intelligence view" width={1536} height={1024} priority /></section>
    <section className="case-content"><aside><span className="section-number">THE CHALLENGE</span></aside><div><h2>Engineering teams feel friction before leadership systems can see it.</h2><p>Delivery dashboards often focus on output, dates, and status. They can miss the operating conditions that determine whether teams can deliver sustainably: cognitive load, slow build loops, excessive operational toil, unclear ownership, onboarding drag, platform gaps, and recurring blocked dependencies.</p></div></section>
    <section className="case-system"><span className="section-number">THE OPERATING SYSTEM</span><div className="case-grid"><article><b>01</b><h3>Model team experience as system evidence</h3><p>Every team has synthetic signals across flow efficiency, delivery reliability, developer experience, platform enablement, operational load, and learning health.</p></article><article><b>02</b><h3>Score the Engineering Experience Index</h3><p>The index combines weighted dimensions with explainable drivers, making it clear why a team is thriving, healthy, strained, or in need of intervention.</p></article><article><b>03</b><h3>Apply hard intervention rules</h3><p>Missing ownership, stale evidence, high incident load, burnout signals, blocked dependencies, and slow build loops cannot hide behind a healthy average.</p></article><article><b>04</b><h3>End in leadership decisions</h3><p>The system turns friction patterns into recommended actions: reduce toil, fund platform improvements, unblock dependencies, clarify ownership, or reset delivery capacity.</p></article></div><p className="case-ecosystem"><b>Illustrative enterprise evidence model:</b> Jira · GitHub · CI/CD pipelines · incident systems · internal developer portals · engineering surveys · onboarding metrics · platform telemetry · DORA-like signals. The public demo uses synthetic data, no API keys, and no employer connections.</p></section>
    <section className="case-content"><aside><span className="section-number">LEADERSHIP SIGNAL</span></aside><div><h2>This is developer experience treated as a strategic operating system.</h2><p>The application demonstrates how a senior technology program leader can connect engineering effectiveness, platform investment, operational resilience, and talent sustainability into a single executive decision model.</p><div className="case-actions"><a href="https://engineering-experience-index.uthamkumar.info" target="_blank" rel="noreferrer">Open live application ↗</a><Link href="/#work">Return to selected work</Link></div></div></section>
    <footer className="case-footer"><span>Engineering Experience Index · Engineering Intelligence Lab</span><Link href="/">uthamkumar.info →</Link></footer>
  </main>;
}
