import Link from "next/link";
import Image from "next/image";

export const metadata = { title: "Dependency Intelligence Case Study | Utham Kumar" };

export default function DependencyIntelligenceCaseStudy() {
  return <main className="case-page">
    <header className="case-nav"><Link href="/">← Utham Kumar</Link><span>Engineering Intelligence Lab / DI-002</span></header>
    <section className="case-hero"><span className="kicker">Enterprise reference implementation</span><h1>Dependency Intelligence</h1><p>Seeing the delivery system—and changing the outcome.</p><div><span><small>Role demonstrated</small><b>Decision-system architect</b></span><span><small>Release</small><b>v0.1.0</b></span><span><small>Data policy</small><b>100% synthetic</b></span></div></section>
    <section className="case-image"><Image src="/dependency-intelligence.png" alt="Dependency Intelligence critical-path visualization" width={1730} height={909} priority /></section>
    <section className="case-content"><aside><span className="section-number">THE CHALLENGE</span></aside><div><h2>Dependency lists show the work. They rarely show the system.</h2><p>Cross-team commitments are spread across backlogs, spreadsheets, design notes, and recurring meetings. Leaders can see red items, but not always the propagation path, provider constraint, evidence quality, or intervention that will protect the outcome.</p></div></section>
    <section className="case-system"><span className="section-number">THE OPERATING SYSTEM</span><div className="case-grid"><article><b>01</b><h3>Define commitments</h3><p>Provider, consumer, acceptance evidence, owner, due date, and downstream outcomes make each dependency actionable.</p></article><article><b>02</b><h3>Explain exposure</h3><p>Seven visible signals and two hard governance rules make prioritization reproducible rather than subjective.</p></article><article><b>03</b><h3>Trace propagation</h3><p>Critical-path and provider-concentration views reveal how one handoff can constrain a portfolio.</p></article><article><b>04</b><h3>Name the move</h3><p>Every exposed commitment is paired with a recommended action, accountable owner, and verification date.</p></article></div><p className="case-ecosystem"><b>Illustrative enterprise evidence model:</b> Jira planning and issue links · service catalogs · CI/CD evidence · Confluence decision records · test-management signals · cloud and observability platforms. The public demo uses synthetic data and no employer connections.</p></section>
    <section className="case-content"><aside><span className="section-number">LEADERSHIP SIGNAL</span></aside><div><h2>This is dependency governance designed as a decision product.</h2><p>The application demonstrates how a principal TPM or engineering delivery leader moves from a list of cross-team asks to a repeatable operating cadence: make the commitment explicit, reveal systemic exposure, protect constrained capacity, and verify that intervention changed the signal.</p><div className="case-actions"><a href="https://dependency-intelligence.uthamkumar.info" target="_blank" rel="noreferrer">Open live reference implementation ↗</a><Link href="/#work">Return to selected work</Link></div></div></section>
    <footer className="case-footer"><span>Dependency Intelligence · Engineering Intelligence Lab</span><Link href="/">uthamkumar.info →</Link></footer>
  </main>;
}
