import Image from "next/image";
import Link from "next/link";

export const metadata = { title: "Cyber Risk Command Center Case Study | Utham Kumar" };

export default function CyberRiskCommandCenterCaseStudy() {
  return <main className="case-page">
    <header className="case-nav"><Link href="/">← Utham Kumar</Link><span>Engineering Intelligence Lab / CR-005</span></header>
    <section className="case-hero"><span className="kicker">Enterprise reference implementation</span><h1>Cyber Risk Command Center</h1><p>Turn material cyber risk into accountable executive action.</p><div><span><small>Role demonstrated</small><b>Cyber risk operating-model architect</b></span><span><small>Release</small><b>v0.1.0</b></span><span><small>Data policy</small><b>100% synthetic</b></span></div></section>
    <section className="case-image"><Image src="/cyber-risk-command-center.png" alt="Cyber Risk Command Center enterprise cyber risk posture view" width={1536} height={1024} priority /></section>
    <section className="case-content"><aside><span className="section-number">THE CHALLENGE</span></aside><div><h2>Cyber programs produce signal faster than leaders can convert it into decisions.</h2><p>Executives need to understand which exposures are material, which controls are evidenced, which remediation commitments are overdue, and which exceptions require acceptance. Traditional dashboards can show telemetry without revealing the operating decision: escalate, fund, accept, or close.</p></div></section>
    <section className="case-system"><span className="section-number">THE OPERATING SYSTEM</span><div className="case-grid"><article><b>01</b><h3>Define material cyber risk</h3><p>Every item has a business service, accountable owner, risk tier, crown-jewel flag, exposure signal, and target closure date.</p></article><article><b>02</b><h3>Score cyber confidence</h3><p>Confidence combines exposure, control effectiveness, remediation velocity, identity, third-party risk, and resilience.</p></article><article><b>03</b><h3>Apply hard escalation rules</h3><p>Internet-exposed crown-jewel findings, overdue critical vulnerabilities, missing owners, privileged-access gaps, and untested recovery proof cannot hide behind a healthy average.</p></article><article><b>04</b><h3>End in executive decisions</h3><p>The command center converts active rules, exceptions, and drivers into a deterministic cyber brief and a decision queue.</p></article></div><p className="case-ecosystem"><b>Illustrative enterprise evidence model:</b> vulnerability management · SIEM/SOC coverage · IAM/PAM evidence · supplier assurance · GRC exceptions · Jira/ServiceNow remediation workflow · resilience testing. The public demo uses synthetic data, no API keys, and no employer connections.</p></section>
    <section className="case-content"><aside><span className="section-number">LEADERSHIP SIGNAL</span></aside><div><h2>This is cyber risk governance designed as a leadership operating system.</h2><p>The application demonstrates how a senior technology program leader can connect security, engineering, operations, risk, and executive sponsors around the same evidence model: what is material, who owns it, why it is escalated, and what action changes the risk posture.</p><div className="case-actions"><a href="https://cyber-risk-command-center.uthamkumar.info" target="_blank" rel="noreferrer">Open live application ↗</a><Link href="/#work">Return to selected work</Link></div></div></section>
    <footer className="case-footer"><span>Cyber Risk Command Center · Engineering Intelligence Lab</span><Link href="/">uthamkumar.info →</Link></footer>
  </main>;
}
